name: Deploy master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: Create ENV file
      run: |
        cat > config.prod.yml << EOF
        ${{ secrets.ENV }}
        EOF

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy Lambda functions
      run: SLS_DEBUG=* sls deploy -s prod
